import '@external/form-item/style/css'
import '@external/tooltip/style/css'
// import '@external/icon/style/css'
import '@external/autocomplete/style/css'
import '@external/cascader/style/css'
import '@external/checkbox/style/css'
import '@external/checkbox-group/style/css'
import '@external/color-picker/style/css'
import '@external/date-picker/style/css'
import '@external/input-number/style/css'
import '@external/radio-group/style/css'
import '@external/radio/style/css'
import '@external/rate/style/css'
import '@external/select/style/css'
import '@external/option/style/css'
import '@external/slider/style/css'
import '@external/switch/style/css'
import '@external/time-picker/style/css'
import '@external/time-select/style/css'
import '@external/input/style/css'
import '@external/text/style/css'

import '@plus-pro-components/components/radio/style/css'
import '@plus-pro-components/components/date-picker/style/css'
import '@plus-pro-components/components/input-tag/style/css'

import '@plus-pro-components/theme-chalk/plus-form-item.css'
