import '@external/form-item/style/index'
import '@external/tooltip/style/index'
// import '@external/icon/style/index'
import '@external/autocomplete/style/index'
import '@external/cascader/style/index'
import '@external/checkbox/style/index'
import '@external/checkbox-group/style/index'
import '@external/color-picker/style/index'
import '@external/date-picker/style/index'
import '@external/input-number/style/index'
import '@external/radio-group/style/index'
import '@external/radio/style/index'
import '@external/rate/style/index'
import '@external/select/style/index'
import '@external/option/style/index'
import '@external/slider/style/index'
import '@external/switch/style/index'
import '@external/time-picker/style/index'
import '@external/time-select/style/index'
import '@external/input/style/index'
import '@external/text/style/index'

import '@plus-pro-components/components/radio/style/index'
import '@plus-pro-components/components/date-picker/style/index'
import '@plus-pro-components/components/input-tag/style/index'

import '@plus-pro-components/theme-chalk/src/form-item.scss'
