import '@external/table/style/css'
import '@external/table-column/style/css'
import '@external/button/style/css'
import '@external/link/style/css'
import '@external/tooltip/style/css'
import '@external/message-box/style/css'
import '@external/dropdown/style/css'
import '@external/dropdown-menu/style/css'
import '@external/dropdown-item/style/css'

import '@plus-pro-components/components/display-item/style/css'
import '@plus-pro-components/components/popover/style/css'
import '@plus-pro-components/components/pagination/style/css'

import '@plus-pro-components/theme-chalk/plus-table.css'
